package onjlib.gui;
/*
	A basic extension of the java.awt.Dialog class
 */

import java.awt.*;

public class OKDialog extends Dialog
{
	AnswerListener m_handler;
	public OKDialog(Frame parent, boolean modal)
	{
		super(parent, modal);

		// This code is automatically generated by Visual Cafe when you add
		// components to the visual environment. It instantiates and initializes
		// the components. To modify the code, only use code syntax that matches
		// what Visual Cafe can generate, or Visual Cafe may be unable to back
		// parse your Java file into its visual environment.
		//{{INIT_CONTROLS
		setLayout(null);
		setSize(291,161);
		setVisible(false);
		txtLabel.setText("Are you sure ?");
		add(txtLabel);
		txtLabel.setFont(new Font("Dialog", Font.BOLD, 12));
		txtLabel.setBounds(36,36,221,29);
		okButton.setLabel("OK");
		add(okButton);
		okButton.setBackground(java.awt.Color.lightGray);
		okButton.setFont(new Font("Dialog", Font.BOLD, 12));
		okButton.setBounds(36,96,88,36);
		cancelButton.setLabel("Cancel");
		add(cancelButton);
		cancelButton.setBackground(java.awt.Color.lightGray);
		cancelButton.setFont(new Font("Dialog", Font.BOLD, 12));
		cancelButton.setBounds(168,96,88,36);
		setTitle("OK Dialog");
		//}}

		//{{REGISTER_LISTENERS
		SymWindow aSymWindow = new SymWindow();
		this.addWindowListener(aSymWindow);
		SymAction lSymAction = new SymAction();
		okButton.addActionListener(lSymAction);
		cancelButton.addActionListener(lSymAction);
		//}}
	}

	public void addNotify()
	{
		// Record the size of the window prior to calling parents addNotify.
		Dimension d = getSize();

		super.addNotify();

		if (fComponentsAdjusted)
			return;

		// Adjust components according to the getInsets
		setSize(getInsets().left + getInsets().right + d.width, getInsets().top + getInsets().bottom + d.height);
		Component components[] = getComponents();
		for (int i = 0; i < components.length; i++)
		{
			Point p = components[i].getLocation();
			p.translate(getInsets().left, getInsets().top);
			components[i].setLocation(p);
		}
		fComponentsAdjusted = true;
	}

	// Used for addNotify check.
	boolean fComponentsAdjusted = false;


	public OKDialog(Frame parent, String title, boolean modal)
	{
		this(parent, modal);
		setTitle(title);
	}
	public void addAnswerListener(AnswerListener ai)
	{
		m_handler = ai;
	}



	/**
	 * Shows or hides the component depending on the boolean flag b.
	 * @param b  if true, show the component; otherwise, hide the component.
	 * @see java.awt.Component#isVisible
	 */
	public void setVisible(boolean b)
	{
		if(b)
		{
			Rectangle bounds = getParent().getBounds();
			Rectangle abounds = getBounds();

			setLocation(bounds.x + (bounds.width - abounds.width)/ 2,
				 bounds.y + (bounds.height - abounds.height)/2);
		}
		super.setVisible(b);
	}

	//{{DECLARE_CONTROLS
	java.awt.Label txtLabel = new java.awt.Label();
	java.awt.Button okButton = new java.awt.Button();
	java.awt.Button cancelButton = new java.awt.Button();
	//}}

	class SymWindow extends java.awt.event.WindowAdapter
	{
		public void windowClosing(java.awt.event.WindowEvent event)
		{
			Object object = event.getSource();
			if (object == OKDialog.this)
				Dialog1_WindowClosing(event);
		}
	}

	void Dialog1_WindowClosing(java.awt.event.WindowEvent event)
	{
		setVisible(false);
	}

	class SymAction implements java.awt.event.ActionListener
	{
		public void actionPerformed(java.awt.event.ActionEvent event)
		{
			Object object = event.getSource();
			if (object == okButton)
				okButton_ActionPerformed(event);
			else if (object == cancelButton)
				cancelButton_ActionPerformed(event);
		}
	}

	void okButton_ActionPerformed(java.awt.event.ActionEvent event)
	{
		// to do: code goes here.
		dispose();
		m_handler.doAction(AnswerListener.ANSWER_OK);

	}

	void cancelButton_ActionPerformed(java.awt.event.ActionEvent event)
	{
		// to do: code goes here
		dispose();
		m_handler.doAction(AnswerListener.ANSWER_CANCEL);
	}

	public static void main(String argv[])
	{
		Frame f = new Frame();
		YNHandler ynHandler = new YNHandler();

		OKDialog okd = new OKDialog(f,"OKDialog",false);
		okd.addAnswerListener(ynHandler);
		okd.show();
		System.out.println("after show");


	}

}
